### ISSUE TITLE
Trouble merging statistics in gwas.py merge-regenie 

### ISSUE THREAD

**Issue by JacobBergstedt** [comorment/containers#14]
Something goes wrong on my end with gwas.py merge-regenie. Both run_regenie1 and run_regenie2 run as expected but then I get the following error for merge-regenie. Looks like something goes wrong in the join.

jacber@sens2017599-b10:~/nordic_gwas/basic$ $PYTHON ~/gwas.py merge-regenie --maf 0.1 --sumstats out/run_chr@_MDD_broad.regenie --basename out/run_chr@ --out out/run_MDD_broad  --chr2use 1,2
***********************************************************************
* gwas.py: pipeline for GWAS analysis
* Version 1.1.0
* (C) 2021 Oleksandr Frei, Bayram Akdeniz and Alexey A. Shadrin
* Norwegian Centre for Mental Disorders Research / University of Oslo
* Centre for Bioinformatics / University of Oslo
* GNU General Public License v3
***********************************************************************
Call: 
/home/jacber/gwas.py merge-regenie \
        --maf 0.1 \
        --sumstats out/run_chr@_MDD_broad.regenie \
        --basename out/run_chr@ \
        --out out/run_MDD_broad \
        --chr2use 1,2
Beginning analysis at Mon Aug 23 09:19:46 2021 by jacber, host sens2017599-b10.uppmax.uu.se
Traceback (most recent call last):
  File "/home/jacber/gwas.py", line 1908, in <module>
    args.func(args, log)
  File "/home/jacber/gwas.py", line 838, in merge_regenie
    df, info_col = apply_filters(args, df)
  File "/home/jacber/gwas.py", line 760, in apply_filters
    df = pd.merge(df, maf, how='left', on='SNP')
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 89, in merge
    return op.get_result()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 684, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 909, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 887, in _get_join_indexers
    return get_join_indexers(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1441, in get_join_indexers
    return join_func(lkey, rkey, count, **kwargs)
  File "pandas/_libs/join.pyx", line 109, in pandas._libs.join.left_outer_join
MemoryError: Unable to allocate 446. GiB for an array with shape (59901284770,) and data type int64

**Comment by ofrei** [comment]
@JacobBergstedt thanks for reporting, looking into this...

**Comment by ofrei** [comment]
@JacobBergstedt could you check whether there are lines with a duplicated value in SNP column of your .bim file?

The pd.merge tries to allocated data frame with 59.901.284.770 entries - this should not be happening. The only explanation for this if there are duplicated entires, because then pd.join will do a "cartesian product" among entries with duplicated key.

**Comment by JacobBergstedt** [comment]
My fault sorry!! It was because of unannotated variants in the vcf files.
